### ISSUE TITLE
XYZ の移動距離

### ISSUE THREAD

**Issue by hysdtkr-work** [iztn/Marlin-for-Z#1]

**Comment by naito7** [comment]
モータードライバをTMC?TMS?にしないといけないらしい

**Comment by hysdtkr-work** [comment]
TMC2208 に変更しないと移動距離があわない

**Comment by hysdtkr-work** [comment]
XYZ全方向について移動距離が合わない

**Comment by hysdtkr-work** [comment]
Marlin\Configuration.h
行146－163を変更するとよさそう
自分たちが使っているのはTMC2226だがソースコメントを見るとTMC2208を使えとのことらしい

**Comment by hysdtkr-work** [comment]
Z軸だけ移動速度が遅かった問題は対応済みを確認しました
